Fix 9
GAMS-Organization/GAMS-Repository pull request #137
Opened 2022-06-29 20:46 UTC by javiSicardi

2022-06-30 20:14 UTC, AleMinacori commented
![imagen](https://user-images.githubusercontent.com/22301272/176769235-e522a347-7b54-412f-b85b-3e1580e62638.png)

Tenemos que hacer un poco mas grande el GridItem que contiene al dropdown para que se vea todo en una línea

2022-07-15 14:45 UTC, AleMinacori requested changes
Hay que modificar las cosas marcadas

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/components/Stock/UpdateStock.jsx
> +    console.log(this.state.current);
borrar este console.log

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/components/Stock/UpdateStock.jsx
> +              </GridContainer>
En lugar de tener un GridContainer > GridItem > CardFooter > Button y luego otro > GridItem > CardFooter > Button, lo ideal es que la estructura sea CardFooter > GridContainer > GridItem > Button y otro GridItem > Button

De esta manera se eliminaría un CardFooter y quedaría mejor estructurado el componente Card

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/components/Stock/ViewDepartureConsumption.jsx
> +            </GridContainer>
cambiar orden por CardFooter > GridContainer > GridItem > Button

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/components/Stock/ViewEntryPurchase.jsx
> +            </GridContainer>
cambiar orden por CardFooter > GridContainer > GridItem > Button

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/sections/Users/UpdateUserSection.jsx
> +    //const fields = ['id', 'name', 'surname', 'email', 'roles'];
borrar linea comentada

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/sections/Users/UpdateUserSection.jsx
> +                {/*<GridItem xs={12} sm={12} md={1}>
si no sirve mas lo comentado, sacarlo

2022-07-15 14:45 UTC, AleMinacori commented on packages/website/src/views/sections/WorkOrder/DetailWorkOrderSection.jsx
> +            <GridContainer justify={'center'}>
cambiar orden por CardFooter > GridContainer > GridItem > Button

2022-07-15 15:31 UTC, AleMinacori commented
Otra cosa que noto, en lo que son las órdenes de trabajo y en todos los modal que sean de creación de alguna solicitud, las fechas, si no se van a poder editar, entonces que no aparezcan directamente como un campo.... hacer lo mismo que con los id

2022-07-18 21:20 UTC, javiSicardi commented on packages/website/src/views/components/Stock/UpdateStock.jsx
> +    console.log(this.state.current);
listo

2022-07-18 21:55 UTC, javiSicardi commented on packages/website/src/views/sections/Users/UpdateUserSection.jsx
> +    //const fields = ['id', 'name', 'surname', 'email', 'roles'];
listo

2022-07-18 21:55 UTC, javiSicardi commented on packages/website/src/views/sections/Users/UpdateUserSection.jsx
> +                {/*<GridItem xs={12} sm={12} md={1}>
listo

2022-07-18 21:57 UTC, javiSicardi commented on packages/website/src/views/sections/WorkOrder/DetailWorkOrderSection.jsx
> +            <GridContainer justify={'center'}>
listo

2022-07-18 22:40 UTC, AleMinacori approved these changes

2022-07-18 22:40 UTC, merged