Detail work order
GAMS-Organization/GAMS-Repository pull request #87
Opened 2021-08-04 19:26 UTC by javiSicardi

Closes #86 

se creo la vista y funcionalidad para que se puedan ver los detalles de una orden de trabajo

2021-08-09 23:49 UTC, AleMinacori requested changes
fijate todo lo que marqué

2021-08-09 23:49 UTC, AleMinacori commented on packages/website/src/services/api/products.js
> +  PUT;
¿¿?¿?¿?¿?¿?

2021-08-09 23:49 UTC, AleMinacori commented on packages/website/src/views/sections/WorkOrder/CompleteWorkOrderSection.jsx
> +  };*/
porque comentado?

2021-08-09 23:49 UTC, AleMinacori commented on packages/website/src/views/sections/WorkOrder/CompleteWorkOrderSection.jsx
> +      console.log(response);
console.log a borrar

2021-08-10 22:21 UTC, javiSicardi commented on packages/website/src/services/api/products.js
> +  PUT;
eliminado

2021-08-10 22:24 UTC, javiSicardi commented on packages/website/src/views/sections/WorkOrder/CompleteWorkOrderSection.jsx
> +      console.log(response);
eliminado

2021-08-24 22:55 UTC, AleMinacori approved these changes

2021-08-31 22:47 UTC, javiSicardi commented on packages/website/src/views/sections/WorkOrder/CompleteWorkOrderSection.jsx
> +  };*/
listo

2021-09-02 20:40 UTC, merged